### ISSUE TITLE
Voice Design Guide URL failed

### ISSUE THREAD

**Issue by JensenZhan** [alexa/skill-sample-python-helloworld-classes#11]
Tutorials & Guides
Voice Design Guide - A great resource for learning conversational and voice user interface design.

that url is unaccessable now.

![image](https://user-images.githubusercontent.com/34338102/101270727-df02a480-37b6-11eb-961d-5438e3fcff69.png)

**Comment by aszk** [comment]
Thank you for the feedback. I have updated the link.
